CREATE TABLE [mytable] (
  [TimeZone] TEXT,
  [UTC offset] TEXT,
  [name] TEXT
);

INSERT INTO [mytable] ([TimeZone],[UTC offset],[name])
VALUES
('Pacific/Midway','"UTC-11:00"','"Midway Island"'),
('Pacific/Honolulu','"UTC-10:00"','"Hawaii"'),
('America/Anchorage','"UTC-08:00"','"Alaska"'),
('America/Tijuana','"UTC-07:00"','"Baja California"'),
('America/Los_Angeles','"UTC-07:00"','"Pacific Time US and Canada"'),
('America/Phoenix','"UTC-07:00"','"Arizona"'),
('America/Chihuahua','"UTC-06:00"','"Chihuahua"'),
('America/Denver','"UTC-06:00"','"Mountain Time US and Canada"'),
('America/Belize','"UTC-06:00"','"Central America"'),
('America/Chicago','"UTC-05:00"','"Central Time US and Canada	"'),
('America/Mexico_City','"UTC-05:00"','"Guadalajara"'),
('America/Regina','"UTC-06:00"','"Saskatchewan"'),
('America/Bogota','"UTC-05:00"','"Bogota"'),
('America/Jamaica','"UTC-05:00"','"Kingston'),
('America/New_York','"UTC-04:00"','"Eastern Time US and Canada"'),
('America/Indiana/Indianapolis','"UTC-04:00"','"Indiana East"'),
('America/Caracas','"UTC-04:30"','"Caracas"'),
('America/Asuncion','"UTC-03:00"','"Asuncion"'),
('America/Halifax','"UTC-03:00"','"Atlantic Time Canada"'),
('America/Cuiaba','"UTC-04:00"','"Cuiaba"'),
('America/Manaus','"UTC-04:00"','"Georgetown"'),
('America/St_Johns','"UTC-02:30"','"Newfoundland and Labrador"'),
('America/Sao_Paulo','"UTC-03:00"','"Brasilia"'),
('America/Buenos_Aires','"UTC-03:00"','"Buenos Aires"'),
('America/Cayenne','"UTC-03:00"','"Cayenne"'),
('America/Godthab','"UTC-02:00"','"Greenland"'),
('America/Montevideo','"UTC-03:00"','"Montevideo"'),
('America/Bahia','"UTC-03:00"','"Salvador"'),
('America/Santiago','"UTC-03:00"','"Santiago"'),
('America/Noronha','"UTC-02:00"','"Mid-Atlantic"'),
('Atlantic/Azores','"UTC+00:00"','"Azores"'),
('Atlantic/Cape_Verde','"UTC-01:00"','"Cape Verde Islands"'),
('Europe/London','"UTC+01:00"','"Dublin'),
('Africa/Casablanca','"UTC+01:00"','"Casablanca"'),
('Africa/Monrovia','"UTC+00:00"','"Monrovia"'),
('Europe/Amsterdam','"UTC+02:00"','"Amsterdam"'),
('Europe/Belgrade','"UTC+02:00"','"Belgrade"'),
('Europe/Brussels','"UTC+02:00"','"Brussels"'),
('Europe/Warsaw','"UTC+02:00"','"Sarajevo"'),
('Africa/Algiers','"UTC+01:00"','"West Central Africa"'),
('Africa/Windhoek','"UTC+02:00"','"Windhoek"'),
('Europe/Athens','"UTC+03:00"','"Athens"'),
('Asia/Beirut','"UTC+03:00"','"Beirut"'),
('Africa/Cairo','"UTC+02:00"','"Cairo"'),
('Asia/Damascus','"UTC+03:00"','"Damascus"'),
('EET','"UTC+03:00"','"Eastern Europe"'),
('Africa/Harare','"UTC+02:00"','"Harare"'),
('Europe/Helsinki','"UTC+03:00"','"Helsinki"'),
('Asia/Istanbul','"UTC+03:00"','"Istanbul"'),
('Asia/Jerusalem','"UTC+03:00"','"Jerusalem"'),
('Europe/Kaliningrad','"UTC+02:00"','"Kaliningrad"'),
('Africa/Tripoli','"UTC+02:00"','"Tripoli"'),
('Asia/Amman','"UTC+03:00"','"Amman"'),
('Asia/Baghdad','"UTC+03:00"','"Baghdad"'),
('Asia/Kuwait','"UTC+03:00"','"Kuwait"'),
('Europe/Minsk','"UTC+03:00"','"Minsk"'),
('Europe/Moscow','"UTC+03:00"','"Moscow"'),
('Africa/Nairobi','"UTC+03:00"','"Nairobi"'),
('Asia/Tehran','"UTC+03:30"','"Tehran"'),
('Asia/Muscat','"UTC+04:00"','"Abu Dhabi"'),
('Asia/Baku','"UTC+05:00"','"Baku"'),
('Europe/Samara','"UTC+04:00"','"Izhevsk"'),
('Indian/Mauritius','"UTC+04:00"','"Port Louis"'),
('Asia/Tbilisi','"UTC+04:00"','"Tbilisi"'),
('Asia/Yerevan','"UTC+04:00"','"Yerevan"'),
('Asia/Kabul','"UTC+04:30"','"Kabul"'),
('Asia/Tashkent','"UTC+05:00"','"Tashkent"'),
('Asia/Yekaterinburg','"UTC+05:00"','"Ekaterinburg"'),
('Asia/Karachi','"UTC+05:00"','"Islamabad"'),
('Asia/Kolkata','"UTC+05:30"','"Chennai"'),
('Asia/Colombo','"UTC+05:30"','"Sri Jayawardenepura"'),
('Asia/Katmandu','"UTC+05:45"','"Kathmandu"'),
('Asia/Almaty','"UTC+06:00"','"Astana"'),
('Asia/Dhaka','"UTC+06:00"','"Dhaka"'),
('Asia/Novosibirsk','"UTC+06:00"','"Novosibirsk"'),
('Asia/Rangoon','"UTC+06:30"','"Yangon Rangoon"'),
('Asia/Bangkok','"UTC+07:00"','"Bangkok"'),
('Asia/Krasnoyarsk','"UTC+07:00"','"Krasnoyarsk"'),
('Asia/Chongqing','"UTC+08:00"','"Beijing"'),
('Asia/Irkutsk','"UTC+08:00"','"Irkutsk"'),
('Asia/Kuala_Lumpur','"UTC+08:00"','"Kuala Lumpur"'),
('Australia/Perth','"UTC+08:00"','"Perth"'),
('Asia/Taipei','"UTC+08:00"','"Taipei"'),
('Asia/Ulaanbaatar','"UTC+08:00"','"Ulaanbaatar"'),
('Asia/Tokyo','"UTC+09:00"','"Osaka"'),
('Asia/Seoul','"UTC+09:00"','"Seoul"'),
('Asia/Yakutsk','"UTC+09:00"','"Yakutsk"'),
('Australia/Adelaide','"UTC+10:30"','"Adelaide"'),
('Australia/Darwin','"UTC+09:30"','"Darwin"'),
('Australia/Brisbane','"UTC+10:00"','"Brisbane"'),
('Australia/Canberra','"UTC+11:00"','"Canberra"'),
('Pacific/Guam','"UTC+10:00"','"Guam"'),
('Australia/Hobart','"UTC+11:00"','"Hobart"'),
('Asia/Magadan','"UTC+10:00"','"Magadan"'),
('Asia/Vladivostok','"UTC+10:00"','"Vladivostok"'),
('Asia/Srednekolymsk','"UTC+11:00"','"Chokirdakh"'),
('Pacific/Guadalcanal','"UTC+11:00"','"Solomon Islands"'),
('Asia/Anadyr','"UTC+12:00"','"Anadyr"'),
('Pacific/Auckland','"UTC+13:00"','"Auckland"'),
('Pacific/Fiji','"UTC+12:00"','"Fiji Islands"'),
('Pacific/Tongatapu','"UTC+13:00"','"Nuku''alofa"'),
('Pacific/Apia','"UTC+14:00"','"Samoa"');