from .apply_font_style_config import update_font_style
from .apply_font_style_kernel import apply_font_style_to_kernel
from .font_size import get_current_font_size, set_font_size
from .font_style import get_font_names, display_text_with_fonts